---
- hosts: localhost
  vars:
    GOPATH: ~/go
  tasks:
  - include: tasks/homebrew.yml
  - include: tasks/homebrew-casks.yml
  - include: tasks/fish.yml
  - include: tasks/git.yml
  - include: tasks/pip.yml
  - include: tasks/npm.yml
  - include: tasks/go.yml
  - include: tasks/kwm.yml
