---
- name: Copy gitconfig
  copy:
    src: files/.gitconfig
    dest: '{{ ansible_env.HOME }}/.gitconfig'

- name: Copy global gitignore
  copy:
    src: files/.gitignore-global
    dest: '{{ ansible_env.HOME }}/.gitignore-global'
