---

- name: KWM > Create settings dir
  file:
    dest: ~/.kwm
    state: directory
  tags: kwm

- name: KWM > Copy .kwmrc
  copy:
    src: ../files/kwmrc
    dest: ~/.kwm/kwmrc
  tags: kwm

- name: KWM > Enable service
  command: brew services start koekeishiya/kwm/kwm
  tags: kwm
